declare class Tiff {
    private _filename;
    private _tiffPtr;
    private static uniqueIdForFileName;
    private static Module;
    static initialize(options: Tiff.InitializeOptions): void;
    constructor(params: Tiff.Params);
    public width(): number;
    public height(): number;
    public currentDirectory(): number;
    public countDirectory(): number;
    public setDirectory(index: number): void;
    public getField(tag: number): number;
    public readRGBAImage(): ArrayBuffer;
    public toCanvas(): HTMLCanvasElement;
    public toDataURL(): string;
    public close(): void;
    private static createUniqueFileName();
    private static createFileSystemObjectFromBuffer(buffer);
}
declare module Tiff {
    interface InitializeOptions {
        TOTAL_MEMORY?: number;
    }
    interface Params {
        buffer: ArrayBuffer;
    }
    class Exception {
        public message: string;
        public name: string;
        constructor(message: string);
    }
    var Tag: {
        SUBFILETYPE: number;
        OSUBFILETYPE: number;
        IMAGEWIDTH: number;
        IMAGELENGTH: number;
        BITSPERSAMPLE: number;
        COMPRESSION: number;
        PHOTOMETRIC: number;
        THRESHHOLDING: number;
        CELLWIDTH: number;
        CELLLENGTH: number;
        FILLORDER: number;
        DOCUMENTNAME: number;
        IMAGEDESCRIPTION: number;
        MAKE: number;
        MODEL: number;
        STRIPOFFSETS: number;
        ORIENTATION: number;
        SAMPLESPERPIXEL: number;
        ROWSPERSTRIP: number;
        STRIPBYTECOUNTS: number;
        MINSAMPLEVALUE: number;
        MAXSAMPLEVALUE: number;
        XRESOLUTION: number;
        YRESOLUTION: number;
        PLANARCONFIG: number;
        PAGENAME: number;
        XPOSITION: number;
        YPOSITION: number;
        FREEOFFSETS: number;
        FREEBYTECOUNTS: number;
        GRAYRESPONSEUNIT: number;
        GRAYRESPONSECURVE: number;
        RESOLUTIONUNIT: number;
        PAGENUMBER: number;
        COLORRESPONSEUNIT: number;
        TRANSFERFUNCTION: number;
        SOFTWARE: number;
        DATETIME: number;
        ARTIST: number;
        HOSTCOMPUTER: number;
        PREDICTOR: number;
        WHITEPOINT: number;
        PRIMARYCHROMATICITIES: number;
        COLORMAP: number;
        HALFTONEHINTS: number;
        TILEWIDTH: number;
        TILELENGTH: number;
        TILEOFFSETS: number;
        TILEBYTECOUNTS: number;
        BADFAXLINES: number;
        CLEANFAXDATA: number;
        CONSECUTIVEBADFAXLINES: number;
        SUBIFD: number;
        INKSET: number;
        INKNAMES: number;
        NUMBEROFINKS: number;
        DOTRANGE: number;
        TARGETPRINTER: number;
        EXTRASAMPLES: number;
        SAMPLEFORMAT: number;
        SMINSAMPLEVALUE: number;
        SMAXSAMPLEVALUE: number;
        CLIPPATH: number;
        XCLIPPATHUNITS: number;
        YCLIPPATHUNITS: number;
        INDEXED: number;
        JPEGTABLES: number;
        OPIPROXY: number;
        GLOBALPARAMETERSIFD: number;
        PROFILETYPE: number;
        FAXPROFILE: number;
        CODINGMETHODS: number;
        VERSIONYEAR: number;
        MODENUMBER: number;
        DECODE: number;
        IMAGEBASECOLOR: number;
        JPEGPROC: number;
        JPEGIFOFFSET: number;
        JPEGIFBYTECOUNT: number;
        JPEGRESTARTINTERVAL: number;
        JPEGLOSSLESSPREDICTORS: number;
        JPEGPOINTTRANSFORM: number;
        JPEGQTABLES: number;
        JPEGDCTABLES: number;
        JPEGACTABLES: number;
        YCBCRCOEFFICIENTS: number;
        YCBCRSUBSAMPLING: number;
        YCBCRPOSITIONING: number;
        REFERENCEBLACKWHITE: number;
        STRIPROWCOUNTS: number;
        XMLPACKET: number;
        OPIIMAGEID: number;
        REFPTS: number;
        REGIONTACKPOINT: number;
        REGIONWARPCORNERS: number;
        REGIONAFFINE: number;
        MATTEING: number;
        DATATYPE: number;
        IMAGEDEPTH: number;
        TILEDEPTH: number;
        PIXAR_IMAGEFULLWIDTH: number;
        PIXAR_IMAGEFULLLENGTH: number;
        PIXAR_TEXTUREFORMAT: number;
        PIXAR_WRAPMODES: number;
        PIXAR_FOVCOT: number;
        PIXAR_MATRIX_WORLDTOSCREEN: number;
        PIXAR_MATRIX_WORLDTOCAMERA: number;
        WRITERSERIALNUMBER: number;
        COPYRIGHT: number;
        RICHTIFFIPTC: number;
        FRAMECOUNT: number;
        PHOTOSHOP: number;
        EXIFIFD: number;
        ICCPROFILE: number;
        IMAGELAYER: number;
        JBIGOPTIONS: number;
        GPSIFD: number;
        FAXRECVPARAMS: number;
        FAXSUBADDRESS: number;
        FAXRECVTIME: number;
        FAXDCS: number;
        STONITS: number;
        FEDEX_EDR: number;
        INTEROPERABILITYIFD: number;
        DNGVERSION: number;
        DNGBACKWARDVERSION: number;
        UNIQUECAMERAMODEL: number;
        LOCALIZEDCAMERAMODEL: number;
        CFAPLANECOLOR: number;
        CFALAYOUT: number;
        LINEARIZATIONTABLE: number;
        BLACKLEVELREPEATDIM: number;
        BLACKLEVEL: number;
        BLACKLEVELDELTAH: number;
        BLACKLEVELDELTAV: number;
        WHITELEVEL: number;
        DEFAULTSCALE: number;
        DEFAULTCROPORIGIN: number;
        DEFAULTCROPSIZE: number;
        ANALOGBALANCE: number;
        ASSHOTNEUTRAL: number;
        ASSHOTWHITEXY: number;
        BASELINEEXPOSURE: number;
        BASELINENOISE: number;
        BASELINESHARPNESS: number;
        BAYERGREENSPLIT: number;
        LINEARRESPONSELIMIT: number;
        CAMERASERIALNUMBER: number;
        LENSINFO: number;
        CHROMABLURRADIUS: number;
        ANTIALIASSTRENGTH: number;
        SHADOWSCALE: number;
        DNGPRIVATEDATA: number;
        MAKERNOTESAFETY: number;
        BESTQUALITYSCALE: number;
        RAWDATAUNIQUEID: number;
        ORIGINALRAWFILENAME: number;
        ORIGINALRAWFILEDATA: number;
        ACTIVEAREA: number;
        MASKEDAREAS: number;
        ASSHOTICCPROFILE: number;
        ASSHOTPREPROFILEMATRIX: number;
        CURRENTICCPROFILE: number;
        CURRENTPREPROFILEMATRIX: number;
        DCSHUESHIFTVALUES: number;
        FAXMODE: number;
        JPEGQUALITY: number;
        JPEGCOLORMODE: number;
        JPEGTABLESMODE: number;
        FAXFILLFUNC: number;
        PIXARLOGDATAFMT: number;
        DCSIMAGERTYPE: number;
        DCSINTERPMODE: number;
        DCSBALANCEARRAY: number;
        DCSCORRECTMATRIX: number;
        DCSGAMMA: number;
        DCSTOESHOULDERPTS: number;
        DCSCALIBRATIONFD: number;
        ZIPQUALITY: number;
        PIXARLOGQUALITY: number;
        DCSCLIPRECTANGLE: number;
        SGILOGDATAFMT: number;
        SGILOGENCODE: number;
        LZMAPRESET: number;
        PERSAMPLE: number;
    };
}
